gh-365: render notebook outputs on rtd
glass-dev/glass pull request #367
Opened 2024-10-15 13:27 UTC by Saransh-cpp

Notebooks now run on RTD so that the (updated) cell outputs can be displayed in the documentation.

Closes: #365

2024-10-24 13:38 UTC, ntessore commented
Great work @Saransh-cpp! Can you revert the changes to the .ipynb files, which will be nothing but updated timestamps and redrawn plots?

2024-10-24 13:44 UTC, ntessore commented on .github/workflows/examples.yml
> +          path: examples/**/*.html
I think this now executes all of the examples twice: once with `jupyter execute examples/**/*.ipynb` and once with `jupyter nbconvert --execute`. You could either remove the first step, or I believe you can remove `--execute` from the second step.

2024-10-24 13:45 UTC, ntessore commented
Could you add a dummy file somewhere that triggers the "Test examples" step, to be removed before merging?

2024-10-24 16:50 UTC, paddyroddy commented
> Could we add this to `pre-commit`? This keeps the plots, and removes all metadata which doesn't actually get displayed on [glass.readthedocs.io](https://glass.readthedocs.io) anyway
> 
> ```yaml
> repos:
>   - repo: https://github.com/kynan/nbstripout
>     rev: 0.7.1
>     hooks:
>       - id: nbstripout
>         args:
>           - --keep-output
> ```

Have added this and raised https://github.com/glass-dev/glass/pull/380

2024-11-06 10:58 UTC, Saransh-cpp commented
The artifact upload worked - https://github.com/glass-dev/glass/actions/runs/11701933760

2024-11-07 11:06 UTC, paddyroddy requested changes

2024-11-07 11:06 UTC, paddyroddy commented on glass/remove_me.py
> +"""to test example artifacts."""
Should this be removed?

2024-11-07 11:06 UTC, paddyroddy commented on .github/workflows/examples.yml
> +          path: examples/**/*.html
Just to keep in line with #388
```suggestion

      - name: Generate HTML
        run: nox -s examples -- html
        env:
          FORCE_COLOR: 1

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: Examples
          path: examples/**/*.html
```

2024-11-07 11:28 UTC, Saransh-cpp commented on glass/remove_me.py
> +"""to test example artifacts."""
Yes, was added to trigger the tests.

2024-11-07 11:30 UTC, paddyroddy approved these changes
Looks good!

2024-11-07 20:39 UTC, merged