gh-272: add tests for glass.points
glass-dev/glass pull request #372
Opened 2024-10-16 10:04 UTC by Saransh-cpp

Add tests and bump coverage to 100 for `glass.points`.

Closes: #273

2024-10-17 14:05 UTC, Saransh-cpp commented
I can't seem to hit the following lines -

https://github.com/glass-dev/glass/blob/c020f18422b9f2960a1fd04d3b395749d2135ee6/glass/points.py#L227-L230

@ntessore do you have a specific case in mind that'll hit these lines. Every combination of arguments I have tried results in `q[-1] == count`, `size` is always 0, and putting these values in, it does not matter what `batch` is, the condition is never met.

2024-10-17 15:53 UTC, ntessore commented
> @ntessore do you have a specific case in mind that'll hit these lines. Every combination of arguments I have tried results in `q[-1] == count`, `size` is always 0, and putting these values in, it does not matter what `batch` is, the condition is never met.

Ah, good catch. The reason is that the batching processes 1000 pixels at a time, but we are using HEALPix maps with only 12 pixels as inputs.

Solution: use a higher number of pixels (`npix`) and replace all uses of `12` with `npix`, and add another case where some of the visibility is zero (hence it needs many batches of empty pixels until it finds enough points).

```py
def test_positions_from_delta():  # type: ignore[no-untyped-def]

    # create maps that saturate the batching in the function
    nside = 128
    npix = 12 * nside**2

    # case: single-dimensional input

    ngal = 1e-3
    delta = np.zeros(npix)
    bias = 0.8
    vis = np.ones(npix)

    ...

    # case: only the southern hemisphere is visible

    vis[:vis.size//2] = 0.0

    lon, lat, cnt = catpos(positions_from_delta(ngal, delta, bias, vis))  # type: ignore[no-untyped-call]

    assert cnt.shape == (3, 2)
    assert lon.shape == (cnt.sum(),)
    assert lat.shape == (cnt.sum(),)
```

2024-10-18 09:28 UTC, Saransh-cpp commented
I see, thank for the detailed suggestion, @ntessore! I will apply this to the tests.

2024-10-24 16:53 UTC, paddyroddy requested changes
Can we change the upstream to #368 and fix the typing here?

2024-11-07 20:21 UTC, ntessore commented on tests/test_points.py
> +        positions_from_delta(ngal, np.linspace(-1, -1, 196608), None, vis)
why not `npix` here and below?

2024-11-12 11:35 UTC, Saransh-cpp commented on tests/test_points.py
> +        positions_from_delta(ngal, np.linspace(-1, -1, 196608), None, vis)
Thanks, updated!

2024-11-13 13:21 UTC, ntessore approved these changes
Nice work @Saransh-cpp!

2024-11-13 14:05 UTC, paddyroddy approved these changes
LGTM

2024-11-13 14:05 UTC, merged